/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Bus = IDL.Record({
  'id' : IDL.Text,
  'ligneId' : IDL.Nat,
  'numeroPlaque' : IDL.Text,
  'estEnService' : IDL.Bool,
  'conducteur' : IDL.Text,
});
export const UserId = IDL.Nat;
export const ParamsDebitTrajet = IDL.Record({
  'ligneId' : IDL.Nat,
  'utilisateurId' : UserId,
  'trajetId' : IDL.Text,
  'montant' : IDL.Nat,
  'busId' : IDL.Text,
});
export const TypeTransaction = IDL.Variant({
  'recharge' : IDL.Record({ 'referenceBaridi' : IDL.Text }),
  'debitTrajet' : IDL.Record({
    'ligneId' : IDL.Nat,
    'trajetId' : IDL.Text,
    'busId' : IDL.Text,
  }),
});
export const Timestamp = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'typeTransaction' : TypeTransaction,
  'soldeApres' : IDL.Nat,
  'utilisateurId' : UserId,
  'timestamp' : Timestamp,
  'montant' : IDL.Nat,
});
export const ResultOk_2 = IDL.Variant({ 'ok' : Transaction, 'err' : IDL.Text });
export const ResultOk_3 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const ParamsInscription = IDL.Record({
  'motDePasseHache' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'nomComplet' : IDL.Text,
  'telephone' : IDL.Text,
});
export const Utilisateur = IDL.Record({
  'id' : UserId,
  'dateInscription' : Timestamp,
  'motDePasseHache' : IDL.Text,
  'numeroCarte' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'solde' : IDL.Nat,
  'nomComplet' : IDL.Text,
  'estVerifie' : IDL.Bool,
  'telephone' : IDL.Text,
});
export const ResultOk_1 = IDL.Variant({ 'ok' : Utilisateur, 'err' : IDL.Text });
export const Region = IDL.Variant({
  'naama' : IDL.Null,
  'ainSefra' : IDL.Null,
  'msharia' : IDL.Null,
});
export const Station = IDL.Record({
  'nom' : IDL.Text,
  'ordre' : IDL.Nat,
  'etaMinutes' : IDL.Opt(IDL.Nat),
});
export const Ligne = IDL.Record({
  'id' : IDL.Nat,
  'nom' : IDL.Text,
  'region' : Region,
  'tarif' : IDL.Nat,
  'stations' : IDL.Vec(Station),
  'numero' : IDL.Text,
});
export const FiltreTransactions = IDL.Record({
  'dateFin' : IDL.Opt(Timestamp),
  'ligneId' : IDL.Opt(IDL.Nat),
  'page' : IDL.Nat,
  'dateDebut' : IDL.Opt(Timestamp),
  'parPage' : IDL.Nat,
});
export const PageTransactions = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'elements' : IDL.Vec(Transaction),
  'parPage' : IDL.Nat,
});
export const ResultOk = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const TypeNotification = IDL.Variant({
  'alerte' : IDL.Null,
  'trajet' : IDL.Null,
  'recharge' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'lue' : IDL.Bool,
  'typeNotif' : TypeNotification,
  'utilisateurId' : UserId,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const ParamsRecharge = IDL.Record({
  'utilisateurId' : UserId,
  'montant' : IDL.Nat,
  'referenceBaridi' : IDL.Text,
});

export const idlService = IDL.Service({
  'busParLigne' : IDL.Func([IDL.Nat], [IDL.Vec(Bus)], ['query']),
  'debiterTrajet' : IDL.Func([ParamsDebitTrajet], [ResultOk_2], []),
  'envoyerOtp' : IDL.Func([IDL.Text], [ResultOk_3], []),
  'inscrire' : IDL.Func([ParamsInscription], [ResultOk_1], []),
  'lignesParRegion' : IDL.Func([Region], [IDL.Vec(Ligne)], ['query']),
  'listerLignes' : IDL.Func([], [IDL.Vec(Ligne)], ['query']),
  'listerTransactions' : IDL.Func(
      [UserId, FiltreTransactions],
      [PageTransactions],
      ['query'],
    ),
  'marquerCommeLue' : IDL.Func([IDL.Nat, UserId], [ResultOk], []),
  'mettreAJourProfil' : IDL.Func(
      [UserId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [ResultOk],
      [],
    ),
  'notificationsNonLues' : IDL.Func(
      [UserId],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'obtenirLigne' : IDL.Func([IDL.Nat], [IDL.Opt(Ligne)], ['query']),
  'obtenirProfil' : IDL.Func([UserId], [IDL.Opt(Utilisateur)], ['query']),
  'obtenirSolde' : IDL.Func([UserId], [IDL.Opt(IDL.Nat)], ['query']),
  'rechargerSolde' : IDL.Func([ParamsRecharge], [ResultOk_2], []),
  'seConnecter' : IDL.Func([IDL.Text, IDL.Text], [ResultOk_1], []),
  'toutesNotifications' : IDL.Func(
      [UserId],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'verifierOtp' : IDL.Func([IDL.Text, IDL.Text], [ResultOk], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Bus = IDL.Record({
    'id' : IDL.Text,
    'ligneId' : IDL.Nat,
    'numeroPlaque' : IDL.Text,
    'estEnService' : IDL.Bool,
    'conducteur' : IDL.Text,
  });
  const UserId = IDL.Nat;
  const ParamsDebitTrajet = IDL.Record({
    'ligneId' : IDL.Nat,
    'utilisateurId' : UserId,
    'trajetId' : IDL.Text,
    'montant' : IDL.Nat,
    'busId' : IDL.Text,
  });
  const TypeTransaction = IDL.Variant({
    'recharge' : IDL.Record({ 'referenceBaridi' : IDL.Text }),
    'debitTrajet' : IDL.Record({
      'ligneId' : IDL.Nat,
      'trajetId' : IDL.Text,
      'busId' : IDL.Text,
    }),
  });
  const Timestamp = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'typeTransaction' : TypeTransaction,
    'soldeApres' : IDL.Nat,
    'utilisateurId' : UserId,
    'timestamp' : Timestamp,
    'montant' : IDL.Nat,
  });
  const ResultOk_2 = IDL.Variant({ 'ok' : Transaction, 'err' : IDL.Text });
  const ResultOk_3 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const ParamsInscription = IDL.Record({
    'motDePasseHache' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'nomComplet' : IDL.Text,
    'telephone' : IDL.Text,
  });
  const Utilisateur = IDL.Record({
    'id' : UserId,
    'dateInscription' : Timestamp,
    'motDePasseHache' : IDL.Text,
    'numeroCarte' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'solde' : IDL.Nat,
    'nomComplet' : IDL.Text,
    'estVerifie' : IDL.Bool,
    'telephone' : IDL.Text,
  });
  const ResultOk_1 = IDL.Variant({ 'ok' : Utilisateur, 'err' : IDL.Text });
  const Region = IDL.Variant({
    'naama' : IDL.Null,
    'ainSefra' : IDL.Null,
    'msharia' : IDL.Null,
  });
  const Station = IDL.Record({
    'nom' : IDL.Text,
    'ordre' : IDL.Nat,
    'etaMinutes' : IDL.Opt(IDL.Nat),
  });
  const Ligne = IDL.Record({
    'id' : IDL.Nat,
    'nom' : IDL.Text,
    'region' : Region,
    'tarif' : IDL.Nat,
    'stations' : IDL.Vec(Station),
    'numero' : IDL.Text,
  });
  const FiltreTransactions = IDL.Record({
    'dateFin' : IDL.Opt(Timestamp),
    'ligneId' : IDL.Opt(IDL.Nat),
    'page' : IDL.Nat,
    'dateDebut' : IDL.Opt(Timestamp),
    'parPage' : IDL.Nat,
  });
  const PageTransactions = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'elements' : IDL.Vec(Transaction),
    'parPage' : IDL.Nat,
  });
  const ResultOk = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const TypeNotification = IDL.Variant({
    'alerte' : IDL.Null,
    'trajet' : IDL.Null,
    'recharge' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'lue' : IDL.Bool,
    'typeNotif' : TypeNotification,
    'utilisateurId' : UserId,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const ParamsRecharge = IDL.Record({
    'utilisateurId' : UserId,
    'montant' : IDL.Nat,
    'referenceBaridi' : IDL.Text,
  });
  
  return IDL.Service({
    'busParLigne' : IDL.Func([IDL.Nat], [IDL.Vec(Bus)], ['query']),
    'debiterTrajet' : IDL.Func([ParamsDebitTrajet], [ResultOk_2], []),
    'envoyerOtp' : IDL.Func([IDL.Text], [ResultOk_3], []),
    'inscrire' : IDL.Func([ParamsInscription], [ResultOk_1], []),
    'lignesParRegion' : IDL.Func([Region], [IDL.Vec(Ligne)], ['query']),
    'listerLignes' : IDL.Func([], [IDL.Vec(Ligne)], ['query']),
    'listerTransactions' : IDL.Func(
        [UserId, FiltreTransactions],
        [PageTransactions],
        ['query'],
      ),
    'marquerCommeLue' : IDL.Func([IDL.Nat, UserId], [ResultOk], []),
    'mettreAJourProfil' : IDL.Func(
        [UserId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [ResultOk],
        [],
      ),
    'notificationsNonLues' : IDL.Func(
        [UserId],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'obtenirLigne' : IDL.Func([IDL.Nat], [IDL.Opt(Ligne)], ['query']),
    'obtenirProfil' : IDL.Func([UserId], [IDL.Opt(Utilisateur)], ['query']),
    'obtenirSolde' : IDL.Func([UserId], [IDL.Opt(IDL.Nat)], ['query']),
    'rechargerSolde' : IDL.Func([ParamsRecharge], [ResultOk_2], []),
    'seConnecter' : IDL.Func([IDL.Text, IDL.Text], [ResultOk_1], []),
    'toutesNotifications' : IDL.Func(
        [UserId],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'verifierOtp' : IDL.Func([IDL.Text, IDL.Text], [ResultOk], []),
  });
};

export const init = ({ IDL }) => { return []; };