/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bus {
  'id' : string,
  'ligneId' : bigint,
  'numeroPlaque' : string,
  'estEnService' : boolean,
  'conducteur' : string,
}
export interface FiltreTransactions {
  'dateFin' : [] | [Timestamp],
  'ligneId' : [] | [bigint],
  'page' : bigint,
  'dateDebut' : [] | [Timestamp],
  'parPage' : bigint,
}
export interface Ligne {
  'id' : bigint,
  'nom' : string,
  'region' : Region,
  'tarif' : bigint,
  'stations' : Array<Station>,
  'numero' : string,
}
export interface Notification {
  'id' : bigint,
  'lue' : boolean,
  'typeNotif' : TypeNotification,
  'utilisateurId' : UserId,
  'message' : string,
  'timestamp' : Timestamp,
}
export interface PageTransactions {
  'total' : bigint,
  'page' : bigint,
  'elements' : Array<Transaction>,
  'parPage' : bigint,
}
export interface ParamsDebitTrajet {
  'ligneId' : bigint,
  'utilisateurId' : UserId,
  'trajetId' : string,
  'montant' : bigint,
  'busId' : string,
}
export interface ParamsInscription {
  'motDePasseHache' : string,
  'email' : [] | [string],
  'nomComplet' : string,
  'telephone' : string,
}
export interface ParamsRecharge {
  'utilisateurId' : UserId,
  'montant' : bigint,
  'referenceBaridi' : string,
}
export type Region = { 'naama' : null } |
  { 'ainSefra' : null } |
  { 'msharia' : null };
export type ResultOk = { 'ok' : boolean } |
  { 'err' : string };
export type ResultOk_1 = { 'ok' : Utilisateur } |
  { 'err' : string };
export type ResultOk_2 = { 'ok' : Transaction } |
  { 'err' : string };
export type ResultOk_3 = { 'ok' : string } |
  { 'err' : string };
export interface Station {
  'nom' : string,
  'ordre' : bigint,
  'etaMinutes' : [] | [bigint],
}
export type Timestamp = bigint;
export interface Transaction {
  'id' : bigint,
  'typeTransaction' : TypeTransaction,
  'soldeApres' : bigint,
  'utilisateurId' : UserId,
  'timestamp' : Timestamp,
  'montant' : bigint,
}
export type TypeNotification = { 'alerte' : null } |
  { 'trajet' : null } |
  { 'recharge' : null };
export type TypeTransaction = { 'recharge' : { 'referenceBaridi' : string } } |
  {
    'debitTrajet' : {
      'ligneId' : bigint,
      'trajetId' : string,
      'busId' : string,
    }
  };
export type UserId = bigint;
export interface Utilisateur {
  'id' : UserId,
  'dateInscription' : Timestamp,
  'motDePasseHache' : string,
  'numeroCarte' : string,
  'email' : [] | [string],
  'solde' : bigint,
  'nomComplet' : string,
  'estVerifie' : boolean,
  'telephone' : string,
}
export interface _SERVICE {
  'busParLigne' : ActorMethod<[bigint], Array<Bus>>,
  'debiterTrajet' : ActorMethod<[ParamsDebitTrajet], ResultOk_2>,
  'envoyerOtp' : ActorMethod<[string], ResultOk_3>,
  'inscrire' : ActorMethod<[ParamsInscription], ResultOk_1>,
  'lignesParRegion' : ActorMethod<[Region], Array<Ligne>>,
  'listerLignes' : ActorMethod<[], Array<Ligne>>,
  'listerTransactions' : ActorMethod<
    [UserId, FiltreTransactions],
    PageTransactions
  >,
  'marquerCommeLue' : ActorMethod<[bigint, UserId], ResultOk>,
  'mettreAJourProfil' : ActorMethod<
    [UserId, [] | [string], [] | [string]],
    ResultOk
  >,
  'notificationsNonLues' : ActorMethod<[UserId], Array<Notification>>,
  'obtenirLigne' : ActorMethod<[bigint], [] | [Ligne]>,
  'obtenirProfil' : ActorMethod<[UserId], [] | [Utilisateur]>,
  'obtenirSolde' : ActorMethod<[UserId], [] | [bigint]>,
  'rechargerSolde' : ActorMethod<[ParamsRecharge], ResultOk_2>,
  'seConnecter' : ActorMethod<[string, string], ResultOk_1>,
  'toutesNotifications' : ActorMethod<[UserId], Array<Notification>>,
  'verifierOtp' : ActorMethod<[string, string], ResultOk>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];