/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface ParamsInscription {
    motDePasseHache: string;
    email?: string;
    nomComplet: string;
    telephone: string;
}
export interface PageTransactions {
    total: bigint;
    page: bigint;
    elements: Array<Transaction>;
    parPage: bigint;
}
export type ResultOk_2 = {
    __kind__: "ok";
    ok: Transaction;
} | {
    __kind__: "err";
    err: string;
};
export interface Ligne {
    id: bigint;
    nom: string;
    region: Region;
    tarif: bigint;
    stations: Array<Station>;
    numero: string;
}
export interface ParamsRecharge {
    utilisateurId: UserId;
    montant: bigint;
    referenceBaridi: string;
}
export interface Utilisateur {
    id: UserId;
    dateInscription: Timestamp;
    motDePasseHache: string;
    numeroCarte: string;
    email?: string;
    solde: bigint;
    nomComplet: string;
    estVerifie: boolean;
    telephone: string;
}
export type ResultOk_3 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface ParamsDebitTrajet {
    ligneId: bigint;
    utilisateurId: UserId;
    trajetId: string;
    montant: bigint;
    busId: string;
}
export interface Transaction {
    id: bigint;
    typeTransaction: TypeTransaction;
    soldeApres: bigint;
    utilisateurId: UserId;
    timestamp: Timestamp;
    montant: bigint;
}
export type UserId = bigint;
export interface FiltreTransactions {
    dateFin?: Timestamp;
    ligneId?: bigint;
    page: bigint;
    dateDebut?: Timestamp;
    parPage: bigint;
}
export interface Notification {
    id: bigint;
    lue: boolean;
    typeNotif: TypeNotification;
    utilisateurId: UserId;
    message: string;
    timestamp: Timestamp;
}
export interface Bus {
    id: string;
    ligneId: bigint;
    numeroPlaque: string;
    estEnService: boolean;
    conducteur: string;
}
export type ResultOk_1 = {
    __kind__: "ok";
    ok: Utilisateur;
} | {
    __kind__: "err";
    err: string;
};
export interface Station {
    nom: string;
    ordre: bigint;
    etaMinutes?: bigint;
}
export type ResultOk = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export type TypeTransaction = {
    __kind__: "recharge";
    recharge: {
        referenceBaridi: string;
    };
} | {
    __kind__: "debitTrajet";
    debitTrajet: {
        ligneId: bigint;
        trajetId: string;
        busId: string;
    };
};
export enum Region {
    naama = "naama",
    ainSefra = "ainSefra",
    msharia = "msharia"
}
export enum TypeNotification {
    alerte = "alerte",
    trajet = "trajet",
    recharge = "recharge"
}
export interface backendInterface {
    busParLigne(ligneId: bigint): Promise<Array<Bus>>;
    debiterTrajet(params: ParamsDebitTrajet): Promise<ResultOk_2>;
    envoyerOtp(telephone: string): Promise<ResultOk_3>;
    inscrire(params: ParamsInscription): Promise<ResultOk_1>;
    lignesParRegion(region: Region): Promise<Array<Ligne>>;
    listerLignes(): Promise<Array<Ligne>>;
    listerTransactions(utilisateurId: UserId, filtre: FiltreTransactions): Promise<PageTransactions>;
    marquerCommeLue(notifId: bigint, utilisateurId: UserId): Promise<ResultOk>;
    mettreAJourProfil(id: UserId, email: string | null, telephone: string | null): Promise<ResultOk>;
    notificationsNonLues(utilisateurId: UserId): Promise<Array<Notification>>;
    obtenirLigne(id: bigint): Promise<Ligne | null>;
    obtenirProfil(id: UserId): Promise<Utilisateur | null>;
    obtenirSolde(utilisateurId: UserId): Promise<bigint | null>;
    rechargerSolde(params: ParamsRecharge): Promise<ResultOk_2>;
    seConnecter(telephone: string, motDePasseHache: string): Promise<ResultOk_1>;
    toutesNotifications(utilisateurId: UserId): Promise<Array<Notification>>;
    verifierOtp(telephone: string, code: string): Promise<ResultOk>;
}
import type { FiltreTransactions as _FiltreTransactions, Ligne as _Ligne, Notification as _Notification, PageTransactions as _PageTransactions, ParamsInscription as _ParamsInscription, Region as _Region, ResultOk as _ResultOk, ResultOk_1 as _ResultOk_1, ResultOk_2 as _ResultOk_2, ResultOk_3 as _ResultOk_3, Station as _Station, Timestamp as _Timestamp, Transaction as _Transaction, TypeNotification as _TypeNotification, TypeTransaction as _TypeTransaction, UserId as _UserId, Utilisateur as _Utilisateur } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async busParLigne(arg0: bigint): Promise<Array<Bus>> {
        if (this.processError) {
            try {
                const result = await this.actor.busParLigne(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.busParLigne(arg0);
            return result;
        }
    }
    async debiterTrajet(arg0: ParamsDebitTrajet): Promise<ResultOk_2> {
        if (this.processError) {
            try {
                const result = await this.actor.debiterTrajet(arg0);
                return from_candid_ResultOk_2_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.debiterTrajet(arg0);
            return from_candid_ResultOk_2_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async envoyerOtp(arg0: string): Promise<ResultOk_3> {
        if (this.processError) {
            try {
                const result = await this.actor.envoyerOtp(arg0);
                return from_candid_ResultOk_3_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.envoyerOtp(arg0);
            return from_candid_ResultOk_3_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async inscrire(arg0: ParamsInscription): Promise<ResultOk_1> {
        if (this.processError) {
            try {
                const result = await this.actor.inscrire(to_candid_ParamsInscription_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ResultOk_1_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inscrire(to_candid_ParamsInscription_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ResultOk_1_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async lignesParRegion(arg0: Region): Promise<Array<Ligne>> {
        if (this.processError) {
            try {
                const result = await this.actor.lignesParRegion(to_candid_Region_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lignesParRegion(to_candid_Region_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async listerLignes(): Promise<Array<Ligne>> {
        if (this.processError) {
            try {
                const result = await this.actor.listerLignes();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listerLignes();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async listerTransactions(arg0: UserId, arg1: FiltreTransactions): Promise<PageTransactions> {
        if (this.processError) {
            try {
                const result = await this.actor.listerTransactions(arg0, to_candid_FiltreTransactions_n27(this._uploadFile, this._downloadFile, arg1));
                return from_candid_PageTransactions_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listerTransactions(arg0, to_candid_FiltreTransactions_n27(this._uploadFile, this._downloadFile, arg1));
            return from_candid_PageTransactions_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async marquerCommeLue(arg0: bigint, arg1: UserId): Promise<ResultOk> {
        if (this.processError) {
            try {
                const result = await this.actor.marquerCommeLue(arg0, arg1);
                return from_candid_ResultOk_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.marquerCommeLue(arg0, arg1);
            return from_candid_ResultOk_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async mettreAJourProfil(arg0: UserId, arg1: string | null, arg2: string | null): Promise<ResultOk> {
        if (this.processError) {
            try {
                const result = await this.actor.mettreAJourProfil(arg0, to_candid_opt_n34(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2));
                return from_candid_ResultOk_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mettreAJourProfil(arg0, to_candid_opt_n34(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2));
            return from_candid_ResultOk_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async notificationsNonLues(arg0: UserId): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.notificationsNonLues(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.notificationsNonLues(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async obtenirLigne(arg0: bigint): Promise<Ligne | null> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenirLigne(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenirLigne(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async obtenirProfil(arg0: UserId): Promise<Utilisateur | null> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenirProfil(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenirProfil(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async obtenirSolde(arg0: UserId): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenirSolde(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenirSolde(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async rechargerSolde(arg0: ParamsRecharge): Promise<ResultOk_2> {
        if (this.processError) {
            try {
                const result = await this.actor.rechargerSolde(arg0);
                return from_candid_ResultOk_2_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rechargerSolde(arg0);
            return from_candid_ResultOk_2_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async seConnecter(arg0: string, arg1: string): Promise<ResultOk_1> {
        if (this.processError) {
            try {
                const result = await this.actor.seConnecter(arg0, arg1);
                return from_candid_ResultOk_1_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seConnecter(arg0, arg1);
            return from_candid_ResultOk_1_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async toutesNotifications(arg0: UserId): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.toutesNotifications(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toutesNotifications(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifierOtp(arg0: string, arg1: string): Promise<ResultOk> {
        if (this.processError) {
            try {
                const result = await this.actor.verifierOtp(arg0, arg1);
                return from_candid_ResultOk_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifierOtp(arg0, arg1);
            return from_candid_ResultOk_n32(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Ligne_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ligne): Ligne {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_PageTransactions_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PageTransactions): PageTransactions {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Region_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Region): Region {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ResultOk_1_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResultOk_1): ResultOk_1 {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ResultOk_2_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResultOk_2): ResultOk_2 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_ResultOk_3_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResultOk_3): ResultOk_3 {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ResultOk_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResultOk): ResultOk {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Station_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Station): Station {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_TypeNotification_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TypeNotification): TypeNotification {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_TypeTransaction_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TypeTransaction): TypeTransaction {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Utilisateur_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Utilisateur): Utilisateur {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Ligne]): Ligne | null {
    return value.length === 0 ? null : from_candid_Ligne_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Utilisateur]): Utilisateur | null {
    return value.length === 0 ? null : from_candid_Utilisateur_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    dateInscription: _Timestamp;
    motDePasseHache: string;
    numeroCarte: string;
    email: [] | [string];
    solde: bigint;
    nomComplet: string;
    estVerifie: boolean;
    telephone: string;
}): {
    id: UserId;
    dateInscription: Timestamp;
    motDePasseHache: string;
    numeroCarte: string;
    email?: string;
    solde: bigint;
    nomComplet: string;
    estVerifie: boolean;
    telephone: string;
} {
    return {
        id: value.id,
        dateInscription: value.dateInscription,
        motDePasseHache: value.motDePasseHache,
        numeroCarte: value.numeroCarte,
        email: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.email)),
        solde: value.solde,
        nomComplet: value.nomComplet,
        estVerifie: value.estVerifie,
        telephone: value.telephone
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    nom: string;
    region: _Region;
    tarif: bigint;
    stations: Array<_Station>;
    numero: string;
}): {
    id: bigint;
    nom: string;
    region: Region;
    tarif: bigint;
    stations: Array<Station>;
    numero: string;
} {
    return {
        id: value.id,
        nom: value.nom,
        region: from_candid_Region_n21(_uploadFile, _downloadFile, value.region),
        tarif: value.tarif,
        stations: from_candid_vec_n23(_uploadFile, _downloadFile, value.stations),
        numero: value.numero
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nom: string;
    ordre: bigint;
    etaMinutes: [] | [bigint];
}): {
    nom: string;
    ordre: bigint;
    etaMinutes?: bigint;
} {
    return {
        nom: value.nom,
        ordre: value.ordre,
        etaMinutes: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.etaMinutes))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    page: bigint;
    elements: Array<_Transaction>;
    parPage: bigint;
}): {
    total: bigint;
    page: bigint;
    elements: Array<Transaction>;
    parPage: bigint;
} {
    return {
        total: value.total,
        page: value.page,
        elements: from_candid_vec_n31(_uploadFile, _downloadFile, value.elements),
        parPage: value.parPage
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    lue: boolean;
    typeNotif: _TypeNotification;
    utilisateurId: _UserId;
    message: string;
    timestamp: _Timestamp;
}): {
    id: bigint;
    lue: boolean;
    typeNotif: TypeNotification;
    utilisateurId: UserId;
    message: string;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        lue: value.lue,
        typeNotif: from_candid_TypeNotification_n38(_uploadFile, _downloadFile, value.typeNotif),
        utilisateurId: value.utilisateurId,
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    typeTransaction: _TypeTransaction;
    soldeApres: bigint;
    utilisateurId: _UserId;
    timestamp: _Timestamp;
    montant: bigint;
}): {
    id: bigint;
    typeTransaction: TypeTransaction;
    soldeApres: bigint;
    utilisateurId: UserId;
    timestamp: Timestamp;
    montant: bigint;
} {
    return {
        id: value.id,
        typeTransaction: from_candid_TypeTransaction_n5(_uploadFile, _downloadFile, value.typeTransaction),
        soldeApres: value.soldeApres,
        utilisateurId: value.utilisateurId,
        timestamp: value.timestamp,
        montant: value.montant
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Utilisateur;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Utilisateur;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Utilisateur_n13(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Transaction;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Transaction;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Transaction_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    naama: null;
} | {
    ainSefra: null;
} | {
    msharia: null;
}): Region {
    return "naama" in value ? Region.naama : "ainSefra" in value ? Region.ainSefra : "msharia" in value ? Region.msharia : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alerte: null;
} | {
    trajet: null;
} | {
    recharge: null;
}): TypeNotification {
    return "alerte" in value ? TypeNotification.alerte : "trajet" in value ? TypeNotification.trajet : "recharge" in value ? TypeNotification.recharge : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recharge: {
        referenceBaridi: string;
    };
} | {
    debitTrajet: {
        ligneId: bigint;
        trajetId: string;
        busId: string;
    };
}): {
    __kind__: "recharge";
    recharge: {
        referenceBaridi: string;
    };
} | {
    __kind__: "debitTrajet";
    debitTrajet: {
        ligneId: bigint;
        trajetId: string;
        busId: string;
    };
} {
    return "recharge" in value ? {
        __kind__: "recharge",
        recharge: value.recharge
    } : "debitTrajet" in value ? {
        __kind__: "debitTrajet",
        debitTrajet: value.debitTrajet
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ligne>): Array<Ligne> {
    return value.map((x)=>from_candid_Ligne_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Station>): Array<Station> {
    return value.map((x)=>from_candid_Station_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n36(_uploadFile, _downloadFile, x));
}
function to_candid_FiltreTransactions_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FiltreTransactions): _FiltreTransactions {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_ParamsInscription_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ParamsInscription): _ParamsInscription {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Region_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Region): _Region {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    motDePasseHache: string;
    email?: string;
    nomComplet: string;
    telephone: string;
}): {
    motDePasseHache: string;
    email: [] | [string];
    nomComplet: string;
    telephone: string;
} {
    return {
        motDePasseHache: value.motDePasseHache,
        email: value.email ? candid_some(value.email) : candid_none(),
        nomComplet: value.nomComplet,
        telephone: value.telephone
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateFin?: Timestamp;
    ligneId?: bigint;
    page: bigint;
    dateDebut?: Timestamp;
    parPage: bigint;
}): {
    dateFin: [] | [_Timestamp];
    ligneId: [] | [bigint];
    page: bigint;
    dateDebut: [] | [_Timestamp];
    parPage: bigint;
} {
    return {
        dateFin: value.dateFin ? candid_some(value.dateFin) : candid_none(),
        ligneId: value.ligneId ? candid_some(value.ligneId) : candid_none(),
        page: value.page,
        dateDebut: value.dateDebut ? candid_some(value.dateDebut) : candid_none(),
        parPage: value.parPage
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Region): {
    naama: null;
} | {
    ainSefra: null;
} | {
    msharia: null;
} {
    return value == Region.naama ? {
        naama: null
    } : value == Region.ainSefra ? {
        ainSefra: null
    } : value == Region.msharia ? {
        msharia: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
